services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
      - ./ssl:/app/ssl:ro
    depends_on:
      - frontend

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - ./ssl:/app/ssl:ro
    environment:
      - CHOKIDAR_USEPOLLING=true
